import { Button } from "../../components/common/Button";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import { clearAutoShadowFailures } from "../../store/scenarioSlice";

/**
 * Bulk-removes every `autoGenerated` failure card in one step. The button
 * that *generates* them ("Автоматически отключать спутники в тени") lives in
 * Settings' "Солнце и терминатор" group, not here — but the resulting cards
 * land in this same sidebar list alongside manual ones, so clearing them
 * belongs next to that list rather than next to the button that made them.
 */
export function ClearAutoShadowFailures() {
  const dispatch = useAppDispatch();
  const autoCount = useAppSelector(
    (s) => s.scenario.overrides.added_failures.filter((f) => f.autoGenerated).length,
  );

  if (autoCount === 0) return null;

  return (
    <Button variant="ghost" icon="reset" onClick={() => dispatch(clearAutoShadowFailures())}>
      Очистить авто-сгенерированные отказы ({autoCount})
    </Button>
  );
}
