import { useState } from "react";
import { Button } from "../../components/common/Button";
import { Modal } from "../../components/common/Modal";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import { addAutoShadowFailures } from "../../store/scenarioSlice";
import { DEFAULT_SIM_DATE, type SatelliteFailure } from "../../domain";
import { findShadowIntervals } from "../../utils/shadowFailures";
import { sunDirectionEci } from "../../utils/sun";
import styles from "./ShadowAutoFailuresTrigger.module.css";

/**
 * Finds every interval where a satellite is eclipsed by Earth (per the
 * simulation date set just above, in the same "Солнце и терминатор" group)
 * and offers to add them to `added_failures` as ordinary failure cards,
 * badged `autoGenerated`. Lives in Settings rather than the sidebar's
 * failures editor because it's a Sun-model action, not a manual-failure
 * action — the resulting cards (and "Очистить авто-сгенерированные отказы")
 * still show up in the sidebar's failures list, right where manual ones do.
 * Reuses the last computed `series` directly — the date doesn't affect
 * orbital mechanics, so no recompute is needed to preview or re-run this
 * after changing it.
 */
export function ShadowAutoFailuresTrigger() {
  const dispatch = useAppDispatch();
  const series = useAppSelector((s) => s.scenario.series);
  const environment = useAppSelector((s) => s.scenario.effectiveScenario?.environment);
  const simDate = useAppSelector((s) => s.scenario.overrides.sim_date ?? DEFAULT_SIM_DATE);

  const [pending, setPending] = useState<SatelliteFailure[] | null>(null);

  const canRun = Boolean(series && environment);

  const handleClick = (): void => {
    if (!series || !environment) return;
    const uEci = sunDirectionEci(simDate, environment.earth_angle0_deg);
    setPending(findShadowIntervals(series, uEci, environment.earth_angle0_deg));
  };

  const confirmApply = (): void => {
    if (!pending) return;
    dispatch(addAutoShadowFailures(pending));
    setPending(null);
  };

  const satelliteCount = pending ? new Set(pending.map((f) => f.satellite_id)).size : 0;

  return (
    <>
      <Button
        icon="satellite"
        disabled={!canRun}
        title={canRun ? undefined : "Сначала выполните расчёт"}
        onClick={handleClick}
      >
        Автоматически отключать спутники в тени
      </Button>

      {pending && (
        <Modal title="Автоматические отказы по тени" onClose={() => setPending(null)}>
          <p className={styles.confirmText}>
            {pending.length === 0
              ? "На выбранную дату ни один спутник не заходит в тень Земли — отказы не будут добавлены."
              : `Будет добавлено ${pending.length} периодов отказа для ${satelliteCount} спутников — продолжить?`}
          </p>
          <div className={styles.actions}>
            <Button onClick={() => setPending(null)}>Отмена</Button>
            {pending.length > 0 && (
              <Button variant="primary" icon="check" onClick={confirmApply}>
                Добавить
              </Button>
            )}
          </div>
        </Modal>
      )}
    </>
  );
}
