import { useState } from "react";
import { Button } from "../../components/common/Button";
import { Modal } from "../../components/common/Modal";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import { addAutoShadowFailures, clearAutoShadowFailures } from "../../store/scenarioSlice";
import { DEFAULT_SIM_DATE, type SatelliteFailure } from "../../domain";
import { findShadowIntervals } from "../../utils/shadowFailures";
import { sunDirectionEci } from "../../utils/sun";
import styles from "./ShadowAutoFailures.module.css";

/**
 * Finds every interval where a satellite is eclipsed by Earth (per the
 * simulation date in Settings) and offers to add them to `added_failures` as
 * ordinary failure cards, badged `autoGenerated` so they're distinguishable
 * and separately clearable. Reuses the last computed `series` directly — the
 * date doesn't affect orbital mechanics, so no recompute is needed to preview
 * or re-run this after changing it.
 */
export function ShadowAutoFailures() {
  const dispatch = useAppDispatch();
  const series = useAppSelector((s) => s.scenario.series);
  const environment = useAppSelector((s) => s.scenario.effectiveScenario?.environment);
  const simDate = useAppSelector((s) => s.scenario.overrides.sim_date ?? DEFAULT_SIM_DATE);
  const autoCount = useAppSelector(
    (s) => s.scenario.overrides.added_failures.filter((f) => f.autoGenerated).length,
  );

  const [pending, setPending] = useState<SatelliteFailure[] | null>(null);

  const canRun = Boolean(series && environment);

  const handleClick = (): void => {
    if (!series || !environment) return;
    const uEci = sunDirectionEci(simDate, environment.earth_angle0_deg);
    setPending(findShadowIntervals(series, uEci, environment.earth_angle0_deg));
  };

  const confirmApply = (): void => {
    if (!pending) return;
    dispatch(addAutoShadowFailures(pending));
    setPending(null);
  };

  const satelliteCount = pending ? new Set(pending.map((f) => f.satellite_id)).size : 0;

  return (
    <div className={styles.wrap}>
      <Button
        icon="satellite"
        disabled={!canRun}
        title={canRun ? undefined : "Сначала выполните расчёт"}
        onClick={handleClick}
      >
        Автоматически отключать спутники в тени
      </Button>
      {autoCount > 0 && (
        <Button variant="ghost" icon="reset" onClick={() => dispatch(clearAutoShadowFailures())}>
          Очистить авто-сгенерированные отказы ({autoCount})
        </Button>
      )}

      {pending && (
        <Modal title="Автоматические отказы по тени" onClose={() => setPending(null)}>
          <p className={styles.confirmText}>
            {pending.length === 0
              ? "На выбранную дату ни один спутник не заходит в тень Земли — отказы не будут добавлены."
              : `Будет добавлено ${pending.length} периодов отказа для ${satelliteCount} спутников — продолжить?`}
          </p>
          <div className={styles.actions}>
            <Button onClick={() => setPending(null)}>Отмена</Button>
            {pending.length > 0 && (
              <Button variant="primary" icon="check" onClick={confirmApply}>
                Добавить
              </Button>
            )}
          </div>
        </Modal>
      )}
    </div>
  );
}
