/**
 * Finds every interval where a satellite sits in Earth's shadow, over an
 * already-computed series — a pure post-processing pass over
 * `SeriesResult.snapshots` (each already carries Earth-fixed satellite
 * positions per instant), not a new geometry pass. Feeds
 * "Автоматически отключать спутники в тени" (auto shadow-failures): the
 * returned records are plain `SatelliteFailure`s (`autoGenerated: true`), fed
 * straight into the same `added_failures` list the manual editor uses.
 */
import type { SatelliteFailure, SeriesResult } from "../domain";
import type { Vec3 } from "./geometry";
import { isEclipsed, sunDirectionEcefAt } from "./sun";

export function findShadowIntervals(series: SeriesResult, uEci: Vec3, earthAngle0Deg: number): SatelliteFailure[] {
  const failures: SatelliteFailure[] = [];
  const openStart = new Map<string, number>();

  for (const snapshot of series.snapshots) {
    const sunEcef = sunDirectionEcefAt(uEci, earthAngle0Deg, snapshot.t_s);
    for (const sat of snapshot.satellites) {
      const shadowed = isEclipsed(sunEcef, { x: sat.x_km, y: sat.y_km, z: sat.z_km });
      const start = openStart.get(sat.id);
      if (shadowed && start === undefined) {
        openStart.set(sat.id, snapshot.t_s);
      } else if (!shadowed && start !== undefined) {
        failures.push({ satellite_id: sat.id, start_s: start, end_s: snapshot.t_s, autoGenerated: true });
        openStart.delete(sat.id);
      }
    }
  }

  // Close any run still open at the end of the horizon. `horizon_s` is
  // validated as a multiple of `step_s`, so the last grid instant plus one
  // step lands exactly on the scenario's horizon boundary.
  const grid = series.t_grid_s;
  if (grid.length > 0) {
    const stepS = grid.length > 1 ? grid[1]! - grid[0]! : 0;
    const horizonEnd = grid[grid.length - 1]! + stepS;
    for (const [satelliteId, start] of openStart) {
      failures.push({ satellite_id: satelliteId, start_s: start, end_s: horizonEnd, autoGenerated: true });
    }
  }

  return failures;
}
